#include <stdint.h>

#include "blosum62.h"

/* This file is automatically generated using scripts/mkBlosum */

const int32_t BLOSUM62_MATRIX[BLOSUM62_SIZE][BLOSUM62_SIZE] = {
  { 1,-3,-3,-3,-3},
  {-3, 1,-3,-3,-3},
  {-3,-3, 1,-3,-3},
  {-3,-3,-3, 1,-3},
  {-3,-3,-3,-3,-3}
};
